[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  NETLIFY_USE_YARN = "false"
  NODE_ENV = "development"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Preload critical assets
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    audit_url = "https://www.aayushhospitalmpl.com/"
    thresholds = { audits = { speed-index = 3000, first-contentful-paint = 2000, interactive = 5000 } }

# Brotli compression
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Encoding = "br"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Encoding = "br"

# Primary domain redirects (301)
[[redirects]]
  from = "http://aayushhospitalmpl.com/*"
  to = "https://www.aayushhospitalmpl.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://aayushhospitalmpl.com/*"
  to = "https://www.aayushhospitalmpl.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.aayushhospitalmpl.com/*"
  to = "https://www.aayushhospitalmpl.com/:splat"
  status = 301
  force = true

# SPA Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify Image CDN
[[redirects]]
  from = "/images/*"
  to = "/.netlify/images/:splat"
  status = 200

# Primary Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://gatgyhxtgqmzwjatbmzk.supabase.co;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https: blob:;
      font-src 'self' data: https://fonts.gstatic.com;
      connect-src 'self' https://gatgyhxtgqmzwjatbmzk.supabase.co;
      media-src 'self' https://gatgyhxtgqmzwjatbmzk.supabase.co https://voaxktqgbljtsattacbn.supabase.co;
      frame-src 'self' https://www.google.com;
      worker-src 'self' blob:;
      """

# Cache Control for Static Assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"

# Cache Control for Images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"

# Cache Control for Fonts
[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"

# Cache Control for HTML Files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate, stale-while-revalidate=3600"

# Cache Control for Page Data
[[headers]]
  for = "/page-data/*"
  [headers.values]
    Cache-Control = "public, max-age=600, stale-while-revalidate=86400"

# Add compression for fonts and images
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Content-Encoding = "br"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Content-Encoding = "br"

# Development-specific settings
[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true